routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::middleware('auth')->get('/home', 'HomeController@index');

Route::get('/', 'HomeController@index')->name('home');

Route::resource('users', 'UserController', ['except' => 'show']);

Route::resource('roles', 'RoleController', ['except' => 'show']);

Route::resource('permissions', 'PermissionController', ['except' => 'show']);

// not needed
//Route::resource('posts', 'PostController');

// business routes
//Route::resource('subscriptions/subscribe', 'SubscriptionController@subscribe');
Route::resource('subscriptions', 'SubscriptionController', ['except' => ['create', 'show']]);

Route::resource('systems', 'SystemController', ['only' => ['index', 'edit', 'update']]);

Route::resource('recipients', 'RecipientsController', ['except' => ['create', 'show']]);

Route::resource('groups', 'GroupController', ['except' => ['create', 'show']]);

//Route::resource('in', 'OzekiInController');

Route::resource('out', 'OzekiOutController', ['only' => ['index', 'store']]);

Route::resource('credits', 'CreditController', ['only' => ['index', 'create', 'store', 'update']]);

Route::resource('sms-categories', 'SmsCategoryController',  ['only' => ['destroy' ,'edit', 'update', 'store']]);

//Route::resource('memberships', 'MembershipController');

Route::resource('billing', 'BillingController',  ['only' => ['index', 'show', 'edit', 'update']]);

Route::resource('profile', 'CustomerInfoController',  ['only' => ['edit', 'update']]);

Route::resource('reports', 'ReportsController',  ['only' => ['index', 'update', 'store']]);

Route::resource('invoices', 'InvoiceController',  ['only' => ['show', 'store']]);

resources/views/partials/forms/allocate_credit.blade.php
{{ Form::open(array('route' => 'credits.store', 'method' => 'POST')) }}

<div class="form-group{{ $errors->has('credit') ? ' has-error' : '' }}">
    {{ Form::label('name', 'Credit') }}
    {{ Form::text('credit', null, array('class' => 'form-control')) }}
    @if ($errors->has('credit'))
        <span class="help-block">
            <strong>{{ $errors->first('credit') }}</strong>
        </span>
    @endif
</div>

<div class="form-group{{ $errors->has('client') ? ' has-error' : '' }}">
    {{ Form::label('client', 'Allocate Credit To:') }}
    {!! Form::component('customSelect', 'components.select.select_clients', ['name', 'select_tag_attributes', 'option_tag_attributes', 'lists']) !!}
    {!! Form::customSelect('client', ['class="selectpicker form-control show-menu-arrow"',
                                            'data-live-search="true"', 'data-header="Select Client"',
                                             'showSubtext="true"', 'data-width="75%"', 'title="Choose client to allocate credit to"'], [],  $clients)
     !!}
    @if ($errors->has('client'))
        <span class="help-block">
             <strong>{{ $errors->first('client') }}</strong>
        </span>
    @endif
</div>

{!! Form::macro('SubmitBtn',function (){
               return '<button type="submit" class="btn btn-primary"> <i class="fa fa-credit-card" ></i> Allocate Credit </button>';
           }) !!}

<div class="form-group">
    {!! Form::SubmitBtn() !!}
</div>

{{ Form::close() }}

resources/views/partials/forms/create_roles.blade.php
{{ Form::open(array('url' => 'roles')) }}

<fieldset>
    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', null, array('class' => 'form-control')) }}
        @if ($errors->has('name'))
            <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
        @endif
    </div>

    <h5><b>Assign Permissions To Role</b></h5>
    <div class='form-group{{ $errors->has('permissions') ? ' has-error' : '' }}'>
        @if ($errors->has('permissions'))
            <span class="help-block">
                        <strong>{{ $errors->first('permissions') }}</strong>
                    </span>
        @endif
        @foreach ($permissions as $permission)
            {{ Form::checkbox('permissions[]',  $permission->id ) }}
            {{ Form::label($permission->name, ucfirst($permission->name)) }}<br>
        @endforeach
    </div>
</fieldset>
<br>
{{ Form::submit('Add', array('class' => 'btn btn-primary')) }}
{{ Form::close() }}

resources/views/partials/forms/create_users.blade.php
{{ Form::open(array('url' => 'users')) }}

<fieldset>
    <legend>Personal Info</legend>

    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', '', array('class' => 'form-control')) }}
        @if ($errors->has('name'))
            <span class="help-block">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
        @endif
    </div>

    <div class="form-group{{ $errors->has('cellphone_number') ? ' has-error' : '' }}">
        {{ Form::label('cellphone_number', 'Cellphone #') }}
        {{ Form::text('cellphone_number', null, array('class' => 'form-control', 'placeholder' => 'Format: 0812190776')) }}
        @if ($errors->has('cellphone_number'))
            <span class="help-block">
                    <strong>{{ $errors->first('cellphone_number') }}</strong>
                </span>
        @endif

    </div>

    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
        {{ Form::label('email', 'Email') }}
        {{ Form::email('email', '', array('class' => 'form-control')) }}
        @if ($errors->has('email'))
            <span class="help-block">
                    <strong>{{ $errors->first('email') }}</strong>
                </span>
        @endif
    </div>

</fieldset>
<br>


    <div class='form-group{{ $errors->has('roles') ? ' has-error' : '' }}'>
        @if(\Illuminate\Support\Facades\Auth::user()->hasRole('Admin'))
            <fieldset>
                <legend>Roles</legend>
        @endif
            @foreach ($roles as $role)

                {{-- loop through and only show roles applicatable to the client --}}
                @if(\Illuminate\Support\Facades\Auth::user()->hasRole('Client') && $role->name == 'Sub-Client')
                    <div hidden>
                        {{ Form::checkbox('roles[]',  $role->id, array('value'=>true)) }}
                        {{ Form::label($role->name, ucfirst($role->name)) }}<br>
                    </div>
                @elseif(\Illuminate\Support\Facades\Auth::user()->hasRole('Admin'))
                            {{ Form::radio('roles[]',  $role->id ) }}
                            {{ Form::label($role->name, ucfirst($role->name)) }}<br>
                @endif

            @endforeach
        @if(\Illuminate\Support\Facades\Auth::user()->hasRole('Admin'))
            </fieldset>
        @endif
        @if ($errors->has('roles'))
            <span class="help-block">
                    <strong>{{ $errors->first('roles') }}</strong>
            </span>
        @endif
    </div>


<br>
<fieldset>
    <legend>Secure Account</legend>

    <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
        {{ Form::label('password', 'Password') }}<br>
        {{ Form::password('password', array('class' => 'form-control')) }}
        @if ($errors->has('password'))
            <span class="help-block">
                        <strong>{{ $errors->first('password') }}</strong>
                    </span>
        @endif
    </div>

    <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
        {{ Form::label('password', 'Confirm Password') }}<br>
        {{ Form::password('password_confirmation', array('class' => 'form-control')) }}
        @if ($errors->has('password'))
            <span class="help-block">
                        <strong>{{ $errors->first('password') }}</strong>
                    </span>
        @endif
    </div>
</fieldset>

<br>

{!! Form::macro('SubmitBtn',function (){
               return '<button type="submit" class="btn btn-primary"> <i class="fa fa-plus" ></i> Create User </button>';
           }) !!}

<div class="form-group">
    {!! Form::SubmitBtn() !!}
</div>
{{ Form::close() }}

resources/views/partials/forms/edit_billing.blade.php
{{ Form::model($billing, array('route' => array('billing.update', $billing->id), 'method' => 'PUT')) }}
<div class="form-group{{ $errors->has('payment_status') ? ' has-error' : '' }}">
    <fieldset>
        <legend>{{ Form::label('payment_status', 'Payment Status') }}</legend>
        {{ Form::radio('payment_status' ,1, ['class' => ' field', 'checked' => $billing->payment_status? true : false]) }}
        {{ Form::label('', 'Paid') }}
        <br>
        {{ Form::radio('payment_status' ,0, ['class' => ' field', 'checked' => !$billing->payment_status? false : true]) }}
        {{ Form::label('', 'Payment Pending') }}
        @if ($errors->has('payment_status'))
            <span class="help-block">
            <strong>{{ $errors->first('payment_status') }}</strong>
        </span>
        @endif
    </fieldset>
</div>
{{--<div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">--}}
    {{--{{ Form::label('description', 'Description') }}--}}
    {{--{{ Form::textarea('description', null, array('class' => 'form-control')) }}--}}
    {{--@if ($errors->has('description'))--}}
        {{--<span class="help-block">--}}
                        {{--<strong>{{ $errors->first('description') }}</strong>--}}
                    {{--</span>--}}
    {{--@endif--}}
{{--</div>--}}
{!! Form::macro('SubmitBtn',function (){
    return '<button type="submit" class="btn btn-primary"> <i class="fa fa-edit"></i> Update </button>';
}) !!}
{!! Form::SubmitBtn() !!}

{{ Form::close() }}

resources/views/partials/forms/edit_group.blade.php
{{ Form::model($group, array('route' => array('groups.update', $group->id), 'method' => 'PUT')) }}
<fieldset>
    <legend>Group Info</legend>
    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', null, array('class' => 'form-control')) }}
        @if ($errors->has('name'))
            <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
        @endif
    </div>
    <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
        {{ Form::label('description', 'Description') }}
        {{ Form::textarea('description', null, array('class' => 'form-control', 'rows' => 5)) }}
        @if ($errors->has('description'))
            <span class="help-block">
                        <strong>{{ $errors->first('description') }}</strong>
                    </span>
        @endif
    </div>
</fieldset>
<br>
{!! Form::macro('SubmitBtn',function (){
    return '<button type="submit" class="btn btn-primary"> <i class="fa fa-edit"></i> Update </button>';
}) !!}
{!! Form::SubmitBtn() !!}

{{ Form::close() }}

resources/views/partials/forms/edit_membership.blade.php
<div class="col-md-8">
    {{ Form::model($membership, array('route' => array('memberships.update', $membership->id), 'method' => 'PUT')) }}
    <div class="form-group">
        {!! Form::label('name', 'Name:') !!}
        {!! Form::text('name',null, array('class' => 'form-control', 'required')) !!}
    </div>

    <div class="form-group">
        {!! Form::label('keyword', 'Keyword:') !!}
        {!! Form::text('keyword',null, array('class' => 'form-control', 'required')) !!}
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
                {!! Form::label('start_date', 'Starting Date:') !!}
                {{--create datetimepicker component--}}
                {!! Form::component('dateTimePicker', 'components.timepicker.timepicker', ['name', 'id', 'attributes']) !!}
                {!! Form::dateTimePicker('start_date', 'start-date-time-picker' , [])
                 !!}
                @if ($errors->has('start_date'))
                    <span class="help-block">
                                <strong>{{ $errors->first('start_date') }}</strong>
                            </span>
                @endif
            </div>
        </div>
        <div class="col-md-6">
            {{--Validate so that end date is after the selected start date--}}
            <div class="form-group{{ $errors->has('end_date') ? ' has-error' : '' }}">
                {!! Form::label('end_date', 'Ending Date:') !!}
                {{--instantiate datetimepicker component--}}
                {!! Form::dateTimePicker('end_date', 'end-date-time-picker' , [])
                 !!}
                @if ($errors->has('end_date'))
                    <span class="help-block">
                                <strong>{{ $errors->first('end_date') }}</strong>
                            </span>
                @endif
            </div>
        </div>
    </div>
    {!! Form::macro('SubmitBtn',function (){
                 return '<button type="submit" class="btn btn-primary"> <i class="fa fa-edit" ></i> Update Membership </button>';
     }) !!}

    <div class="form-group">
        {!! Form::SubmitBtn() !!}
    </div>

    {{ Form::close() }}
</div>

resources/views/partials/forms/edit_profile.blade.php
{{ Form::model($user, array('route' => array('users.update', \Illuminate\Support\Facades\Crypt::encrypt($user->id)), 'method' => 'PUT')) }}{{-- Form model binding to automatically populate our fields with user data --}}

{{--form name--}}
{{ Form::text('update_profile', null, array('class' => 'form-control', 'value' => 'update_profile', 'hidden')) }}

<fieldset>
    <legend>
        Profile Info
    </legend>
    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', null, array('class' => 'form-control')) }}

        @if ($errors->has('name'))
            <span class="help-block">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
        @endif

    </div>

    <div class="form-group{{ $errors->has('cellphone_number') ? ' has-error' : '' }}">
        {{ Form::label('cellphone_number', 'Cellphone #') }}
        {{ Form::text('cellphone_number', null, array('class' => 'form-control', 'placeholder' => 'Format: 0812190776')) }}

        @if ($errors->has('cellphone_number'))
            <span class="help-block">
                <strong>{{ $errors->first('cellphone_number') }}</strong>
            </span>
        @endif

    </div>

    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
        {{ Form::label('email', 'Email') }}
        {{ Form::email('email', null, array('class' => 'form-control')) }}
        @if ($errors->has('email'))
            <span class="help-block">
                    <strong>{{ $errors->first('email') }}</strong>
                </span>
        @endif
    </div>

    <div class='form-group'>
        @foreach ($roles as $role)
            {{-- loop through and only show roles applicatable to the client --}}

            <div hidden>
                {{ Form::checkbox('roles[]',  $role->id ) }}
                {{ Form::label($role->name, ucfirst($role->name)) }}<br>
            </div>

        @endforeach
    </div>
</fieldset>
<br>
<fieldset>
    <legend>
        Secure Account
    </legend>
    <div class="form-group">
        {{ Form::label('password', 'Password') }}<br>
        {{ Form::password('password', array('class' => 'form-control')) }}
        @if ($errors->has('password'))
            <span class="help-block">
                    <strong>{{ $errors->first('password') }}</strong>
                </span>
        @endif
    </div>

    <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
        {{ Form::label('password_confirmation', 'Confirm Password') }}<br>
        {{ Form::password('password_confirmation', array('class' => 'form-control')) }}
        @if ($errors->has('password_confirmation'))
            <span class="help-block">
                    <strong>{{ $errors->first('password_confirmation') }}</strong>
                </span>
        @endif
    </div>
</fieldset>

<br>

{!! Form::macro('SubmitBtn',function (){
    return '<button type="submit" class="btn btn-primary"> <i class="fa fa-edit"></i> Update User Profile </button>';
}) !!}
{!! Form::SubmitBtn() !!}
{{ Form::close() }}

resources/views/partials/forms/give_users_access_to_groups.blade.php
{{ Form::open(array('route' => 'groups.store', 'method' => 'POST')) }}

<div class="form-group">
    {!! Form::text('give_users_access_to_groups', null, array('hidden', 'value'=>'give_users_access_to_groups')) !!}
</div>

<div class="form-group{{ $errors->has('user') ? ' has-error' : '' }}">
    {{ Form::label('user', 'User:') }}
    {!! Form::component('customSelect', 'components.select.select_clients', ['name', 'select_tag_attributes', 'option_tag_attributes', 'lists']) !!}
    {!! Form::customSelect('user', ['class="selectpicker form-control show-menu-arrow"',
                                            'data-live-search="true"', 'data-header="Select Client"',
                                             'showSubtext="true"', 'data-width="75%"', 'title="Choose user to authorize"'], [],  $users)
     !!}
    @if ($errors->has('user'))
        <span class="help-block">
             <strong>{{ $errors->first('user') }}</strong>
        </span>
    @endif
</div>

<div class="form-group{{ $errors->has('groups') ? ' has-error' : '' }}">
    {!! Form::label('groups', 'Groups:') !!}
    {{--create lists component--}}
    {!! Form::component('customSelect', 'components.select.select_groups', ['name', 'select_tag_attributes', 'option_tag_attributes', 'lists']) !!}
    {!! Form::customSelect('groups[]', ['class="selectpicker form-control show-menu-arrow"',
                            'data-live-search="true"', 'data-header="Select Group"',
                             'showSubtext="true"', 'data-width="75%"', 'title="Choose groups to authorize to user"', 'multiple' ], [],  $groups)
     !!}
    @if ($errors->has('groups'))
        <span class="help-block">
            <strong >{{ $errors->first('groups') }}</strong>
        </span>
    @endif
</div>

{!! Form::macro('SubmitBtn',function (){
       return '<button type="submit" class="btn btn-primary"> <i class="fa fa-superpowers" ></i> Authorize User </button>';
}) !!}

<div class="form-group">
    {!! Form::SubmitBtn() !!}
</div>

{{ Form::close() }}

resources/views/partials/forms/import_bulk_recipients.blade.php
<div class="panel panel-body">
    <div class="row" style="padding-bottom: 10px; margin-left: 3px;">
        <div class="alert alert-important panel panel-body panel-warning col-md-6 ">
            Make sure that your file uses the following headings <b class="text-danger">number</b> and <b
                    class="text-danger">name</b>, however the name is optional!
        </div>
    </div>
    <div class="panel panel-default panel-body">
        <div class="row">
            <class class="form-group">

                <div class="col-md-8">
                    <label for=""> Create <b>Group</b> if it does not exist already </label>
                    <button type="button" id="create_group" class="btn btn-default" data-toggle="modal"
                            data-target="#createGroup">Create group for recipients
                    </button>
                </div>
            </class>
        </div>
    </div>
    @include('includes.modals.create_group')

    <div class="panel panel-default panel-body">
        {!! Form::open(array('route'=>'recipients.store', 'method'=>'POST', 'enctype' => 'multipart/form-data'))  !!}
        {{--{{csrf_field()}}--}}

        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group{{ $errors->has('groups') ? ' has-error' : '' }}">
                        {{--create lists component--}}
                        {!! Form::label('group', 'Add Recipients to group') !!}
                        {!! Form::component('customSelect', 'components.select.select_groups', ['name', 'select_tag_attributes', 'option_tag_attributes', 'lists']) !!}
                        {!! Form::customSelect('group', ['class="selectpicker form-control show-menu-arrow"',
                                                'data-live-search="true"', 'data-header="Select Groups"',
                                                 'showSubtext="true"', 'data-width="75%"', 'title="Select group"', 'required'], [],  $groups)
                         !!}
                        @if ($errors->has('groups'))
                            <span class="help-block">
                				<strong style="color: red">{{ $errors->first('groups') }}</strong>
            				</span>
                        @endif
                    </div>
                </div>
            </div>
        </div>

        {!! Form::label('csv_file', 'Select a CSV Or Excel file to import') !!}
        <div class="form-group panel panel-body panel-default {{ $errors->has('csv_file') ? ' has-error' : '' }}">
            {!! Form::file('csv_file',null, array('class' => 'form-control', 'id'=>'csv_file')) !!}
            {{--<input name="csv_file" id="csv_file" type="file" class="" formenctype="multipart/form-data">--}}
            @if ($errors->has('csv_file'))
                <span class="help-block">
                    <strong>{{ $errors->first('csv_file') }}</strong>
                </span>
            @endif
        </div>

        {{-- used to track the form --}}
        {!! Form::text('contacts_upload_form', null, array('value' => 'contacts_upload_form', 'hidden') ) !!}

        <div class="form-group">
            {!! Form::macro('SubmitBtn',function (){
            return '<button type="submit" class="btn btn-primary"> <i class="fa fa-upload"></i> Upload </button>';
            }) !!}
            {!! Form::SubmitBtn() !!}
        </div>

        {{Form::close()}}
    </div>

</div>

resources/views/partials/forms/reallocate_credit.blade.php
{{ Form::open(array('route' => 'credits.store', 'method' => 'POST')) }}


<div class="form-group{{ $errors->has('reallocate_from') ? ' has-error' : '' }}">
    {{ Form::label('reallocate_from', 'Reallocate Credit From:') }}
    {!! Form::component('customSelect', 'components.select.select_clients', ['name', 'select_tag_attributes', 'option_tag_attributes', 'lists']) !!}
    {!! Form::customSelect('reallocate_from', ['class="selectpicker form-control show-menu-arrow"',
                                            'data-live-search="true"', 'data-header="Select Client"',
                                             'showSubtext="true"', 'data-width="75%"', 'title="Choose client to allocate credit from"'], [],  $clients)
     !!}
    @if ($errors->has('reallocate_from'))
        <span class="help-block">
             <strong>{{ $errors->first('reallocate_from') }}</strong>
        </span>
    @endif
</div>

<div class="form-group{{ $errors->has('credit') ? ' has-error' : '' }}">
    {{ Form::label('name', 'Credit') }}
    {{ Form::number('credit', null, array('class' => 'form-control')) }}
    @if ($errors->has('credit'))
        <span class="help-block">
            <strong>{{ $errors->first('credit') }}</strong>
        </span>
    @endif
</div>

<div class="form-group{{ $errors->has('reallocate_to') ? ' has-error' : '' }}">
    {{ Form::label('reallocate_to', 'Reallocate Credit To:') }}
    {!! Form::component('customSelect', 'components.select.select_clients', ['name', 'select_tag_attributes', 'option_tag_attributes', 'lists']) !!}
    {!! Form::customSelect('reallocate_to', ['class="selectpicker form-control show-menu-arrow"',
                                            'data-live-search="true"', 'data-header="Select Client"',
                                             'showSubtext="true"', 'data-width="75%"', 'title="Choose client to allocate credit to"'], [],  $clients)
     !!}
    @if ($errors->has('reallocate_to'))
        <span class="help-block">
             <strong>{{ $errors->first('reallocate_to') }}</strong>
        </span>
    @endif
</div>

{{ Form::text('reallocate-credit-form', null, array('class' => 'form-control', 'value' => 'reallocate-credit-form', 'hidden')) }}

{!! Form::macro('SubmitBtn',function (){
               return '<button type="submit" class="btn btn-primary"> <i class="fa fa-reply-all" ></i> Reallocate Credit </button>';
}) !!}

<div class="form-group">
    {!! Form::SubmitBtn() !!}
</div>
{{ Form::close() }}

resources/views/partials/forms/recipients.blade.php
{!! Form::open(array('route' => 'out.store', 'method' => 'POST')) !!}

    @include('partials.inputs.msg')

    <div class="form-group{{ $errors->has('receiver') ? ' has-error' : '' }}">
        {!! Form::label('receiver', 'Recipient:') !!}
        {{--create lists component--}}
        {!! Form::component('customSelect', 'components.select.select', ['name', 'select_tag_attributes', 'option_tag_attributes', 'lists']) !!}
        {!! Form::customSelect('receiver[ ]', ['class="selectpicker form-control show-menu-arrow"',
                                'data-live-search="true"', 'data-header="Select recipients"',
                                 'showSubtext="true"', 'data-width="75%"', 'title="Choose your custom contacts"', 'multiple'], [],  $recipients)
         !!}
        @if ($errors->has('receiver'))
            <span class="help-block">
                <strong >{{ $errors->first('receiver') }}</strong>
            </span>
        @endif
    </div>

    @include('components.inputs.category')

    {!! Form::macro('SubmitBtn',function (){
               return '<button type="submit" class="btn btn-primary"> <i class="fa fa-location-arrow"></i> Send Message </button>';
    }) !!}

    <div class="form-group">
        {!! Form::SubmitBtn() !!}
    </div>

{!! Form::close() !!}

resources/views/partials/forms/settings.blade.php
{{ Form::model($settings, array('route' => array('systems.update', $settings->id), 'method' => 'PUT')) }}
<div class="form-group{{ $errors->has('default_sms_rate') ? ' has-error' : '' }}">
    {{ Form::label('default_sms_rate', 'SMS Charge') }}
    {{ Form::number('default_sms_rate', number_format($settings->default_sms_rate, 0), array('class' => 'form-control')) }}
    @if ($errors->has('default_sms_rate'))
        <span class="help-block">
            <strong>{{ $errors->first('default_sms_rate') }}</strong>
        </span>
    @endif
</div>
<div class="form-group{{ $errors->has('telephone') ? ' has-error' : '' }}">
    {{ Form::label('telephone', 'Telephone') }}
    {{ Form::text('telephone', null, array('class' => 'form-control')) }}
    @if ($errors->has('telephone'))
        <span class="help-block">
            <strong>{{ $errors->first('telephone') }}</strong>
        </span>
    @endif
</div>

<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
    {{ Form::label('email', 'Support Email') }}
    {{ Form::email('email', null, array('class' => 'form-control')) }}
    @if ($errors->has('email'))
        <span class="help-block">
            <strong>{{ $errors->first('email') }}</strong>
        </span>
    @endif
</div>

<div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
    {{ Form::label('address', 'Office Address') }}
    {{ Form::textarea('address', null, array('class' => 'form-control', 'rows' => 4)) }}
    @if ($errors->has('address'))
        <span class="help-block">
            <strong>{{ $errors->first('address') }}</strong>
        </span>
    @endif
</div>
{!! Form::macro('SubmitBtn',function (){
    return '<button type="submit" class="btn btn-primary"> <i class="fa fa-edit"></i> Update </button>';
}) !!}
{!! Form::SubmitBtn() !!}

{{ Form::close() }}

resources/views/partials/forms/settings_view.blade.php
{{ Form::model($settings) }}
<div class="form-group{{ $errors->has('default_sms_rate') ? ' has-error' : '' }}">
    {{ Form::label('default_sms_rate', 'SMS Charge') }}
    {{ Form::number('default_sms_rate', number_format($settings->default_sms_rate, 2) , array('class' => 'form-control', 'disabled')) }}
    @if ($errors->has('default_sms_rate'))
        <span class="help-block">
            <strong>{{ $errors->first('default_sms_rate') }}</strong>
        </span>
    @endif
</div>
<div class="form-group{{ $errors->has('telephone') ? ' has-error' : '' }}">
    {{ Form::label('telephone', 'Telephone') }}
    {{ Form::text('telephone', null, array('class' => 'form-control', 'disabled')) }}
    @if ($errors->has('telephone'))
        <span class="help-block">
            <strong>{{ $errors->first('telephone') }}</strong>
        </span>
    @endif
</div>

<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
    {{ Form::label('email', 'Support Email') }}
    {{ Form::email('email', null, array('class' => 'form-control', 'disabled')) }}
    @if ($errors->has('email'))
        <span class="help-block">
            <strong>{{ $errors->first('email') }}</strong>
        </span>
    @endif
</div>

<div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
    {{ Form::label('address', 'Office Address') }}
    {{ Form::textarea('address', null, array('class' => 'form-control', 'rows' => 4, 'disabled')) }}
    @if ($errors->has('address'))
        <span class="help-block">
            <strong>{{ $errors->first('address') }}</strong>
        </span>
    @endif
</div>

@can('Edit System Settings')

    <a href="{{ route('systems.edit', $settings->id) }}" class="btn btn-outline-info pull-left" style="margin-right: 3px;">
        <i class="fa fa-edit"></i> Edit </a>

@endcan

{{ Form::close() }}