routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::middleware('auth')->get('/home', 'HomeController@index');

Route::get('/', 'HomeController@index')->name('home');

Route::resource('users', 'UserController', ['except' => 'show']);

Route::resource('roles', 'RoleController', ['except' => 'show']);

Route::resource('permissions', 'PermissionController', ['except' => 'show']);

// not needed
//Route::resource('posts', 'PostController');

// business routes
//Route::resource('subscriptions/subscribe', 'SubscriptionController@subscribe');
Route::resource('subscriptions', 'SubscriptionController', ['except' => ['create', 'show']]);

Route::resource('systems', 'SystemController', ['only' => ['index', 'edit', 'update']]);

Route::resource('recipients', 'RecipientsController', ['except' => ['create', 'show']]);

Route::resource('groups', 'GroupController', ['except' => ['create', 'show']]);

//Route::resource('in', 'OzekiInController');

Route::resource('out', 'OzekiOutController', ['only' => ['index', 'store']]);

Route::resource('credits', 'CreditController', ['only' => ['index', 'create', 'store', 'update']]);

Route::resource('sms-categories', 'SmsCategoryController',  ['only' => ['destroy' ,'edit', 'update', 'store']]);

//Route::resource('memberships', 'MembershipController');

Route::resource('billing', 'BillingController',  ['only' => ['index', 'show', 'edit', 'update']]);

Route::resource('profile', 'CustomerInfoController',  ['only' => ['edit', 'update']]);

Route::resource('reports', 'ReportsController',  ['only' => ['index', 'update', 'store']]);

Route::resource('invoices', 'InvoiceController',  ['only' => ['show', 'store']]);

resources/views/partials/reporting/data/daily_report.blade.php
    @foreach ($dailyMessages as $dailyMessage)
        <tr>
            <td>{{ $dailyMessage->id }}</td>
            <td>{{ $dailyMessage->date}}</td>
            <td>{{ $dailyMessage->sender->name }}</td>
            <td>{{ $dailyMessage->total_messages_for_the_day }}</td>
            {{--<td>N$ {{ number_format($yearlyMessage->amount, 2) }}</td>--}}
            {{--<td>--}}
            {{--@if($yearlyMessage->payment_status)--}}
            {{--<i style="color: green" class="fa fa-check"></i>--}}
            {{--@else--}}
            {{--<i style="color: red" class="fa fa-times"></i>--}}
            {{--@endif--}}
            {{--</td>--}}
            {{--<td>--}}
            {{--@if($bill->payment_status)--}}
            {{--{{ $bill->payment_date }}--}}
            {{--@else--}}
            {{--{{'pending'}}--}}
            {{--@endif--}}
            {{--</td>--}}
            {{--<td>--}}
            {{--@can('Update Billings')--}}
            {{--<a href="{{ route('billing.edit', $bill->id) }}" class="btn btn-default pull-left" style="margin-right: 3px;">--}}
            {{--<i class="fa fa-edit"></i> </a>--}}
            {{--@endcan--}}

            {{--<a href="{{ route('billing.show', $bill->id) }}" class="btn btn-outline-info pull-left">--}}
            {{--<i class="fa fa-binoculars"></i> </a>--}}

            {{--{!! Form::open(['method' => 'DELETE', 'route' => ['bills.destroy', $bill->id], 'id' => 'delete-form' ]) !!}--}}
            {{--{!! Form::macro('SubmitBtn',function (){--}}
            {{--return '<button type="submit" class="btn btn-default"> <i class="fa fa-remove" style="color: red;"></i> </button>';--}}
            {{--}) !!}--}}
            {{--{!! Form::SubmitBtn() !!}--}}
            {{--{!! Form::close() !!}--}}

            {{--</td>--}}
        </tr>
    @endforeach

resources/views/partials/reporting/data/fa_monthly.blade.php
<?php $total = 0 ?>
@foreach ($bills as $bill)
    <tr>
        <td>{{ $bill->id }}</td>
        <td>{{ $bill->subscription_month }}</td>
        <td>{{ $bill->client->name }}</td>
        <td>N$ {{ number_format($bill->amount, 2) }}</td>
    <?php $total += $bill->amount ?>


    {{--{!! Form::open(['method' => 'DELETE', 'route' => ['bills.destroy', $bill->id], 'id' => 'delete-form' ]) !!}--}}
    {{--{!! Form::macro('SubmitBtn',function (){--}}
    {{--return '<button type="submit" class="btn btn-default"> <i class="fa fa-remove" style="color: red;"></i> </button>';--}}
    {{--}) !!}--}}
    {{--{!! Form::SubmitBtn() !!}--}}
    {{--{!! Form::close() !!}--}}

    {{--</td>--}}
    {{--</tr>--}}
@endforeach
<tr>
    <td></td>
    <td></td>
    <td>Total</td>
    <td><strong>N$ {{ number_format($total, 2) }}</strong></td>
</tr>

resources/views/partials/reporting/data/monthly_report.blade.php
    @foreach ($monthlyMessages as $monthlyMessage)
        <tr>
            <td>{{ $monthlyMessage->id }}</td>
            <td>{{ $monthlyMessage->month}}</td>
            <td>{{ $monthlyMessage->sender->name }}</td>
            <td>{{ $monthlyMessage->total_messages_for_the_month }}</td>
            {{--<td>N$ {{ number_format($yearlyMessage->amount, 2) }}</td>--}}
            {{--<td>--}}
            {{--@if($yearlyMessage->payment_status)--}}
            {{--<i style="color: green" class="fa fa-check"></i>--}}
            {{--@else--}}
            {{--<i style="color: red" class="fa fa-times"></i>--}}
            {{--@endif--}}
            {{--</td>--}}
            {{--<td>--}}
            {{--@if($bill->payment_status)--}}
            {{--{{ $bill->payment_date }}--}}
            {{--@else--}}
            {{--{{'pending'}}--}}
            {{--@endif--}}
            {{--</td>--}}
            <td>
                {!! Form::open(['method' => 'POST', 'route' => ['reports.store'] ]) !!}
                {!! Form::text('expand-month',$monthlyMessage->sender->id,array('hidden')) !!}
                {!! Form::text('month',$monthlyMessage->id,array('hidden')) !!}
                {!! Form::macro('SubmitBtn',function (){
                    return '<button type="submit" class="btn btn-default"> <i class="fa fa-binoculars" ></i> </button>';
                }) !!}
                {!! Form::SubmitBtn() !!}
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach

resources/views/partials/reporting/data/yearly_report.blade.php
 @foreach ($yearlyMessages as $yearlyMessage)
        <tr>
            <td>{{ $yearlyMessage->id }}</td>
            <td>{{ $yearlyMessage->year}}</td>
            <td>{{ $yearlyMessage->sender->name }}</td>
            <td>{{ $yearlyMessage->total_messages_for_the_year }}</td>
            {{--<td>N$ {{ number_format($yearlyMessage->amount, 2) }}</td>--}}
            {{--<td>--}}
            {{--@if($yearlyMessage->payment_status)--}}
            {{--<i style="color: green" class="fa fa-check"></i>--}}
            {{--@else--}}
            {{--<i style="color: red" class="fa fa-times"></i>--}}
            {{--@endif--}}
            {{--</td>--}}
            {{--<td>--}}
            {{--@if($bill->payment_status)--}}
            {{--{{ $bill->payment_date }}--}}
            {{--@else--}}
            {{--{{'pending'}}--}}
            {{--@endif--}}
            {{--</td>--}}
            <td>
                {{--@can('Update Billings')--}}
                {{--<a href="{{ route('billing.edit', $bill->id) }}" class="btn btn-default pull-left" style="margin-right: 3px;">--}}
                {{--<i class="fa fa-edit"></i> </a>--}}
                {{--@endcan--}}

                {{--<a href="{{ route('billing.show', $bill->id) }}" class="btn btn-outline-info pull-left">--}}
                {{--<i class="fa fa-binoculars"></i> </a>--}}

                {!! Form::open(['method' => 'POST', 'route' => ['reports.store'] ]) !!}
                    {!! Form::text('expand-year',$yearlyMessage->sender->id,array('hidden')) !!}
                    {!! Form::text('year',$yearlyMessage->id,array('hidden')) !!}
                    {!! Form::macro('SubmitBtn',function (){
                        return '<button type="submit" class="btn btn-default"> <i class="fa fa-binoculars" ></i> </button>';
                    }) !!}
                    {!! Form::SubmitBtn() !!}
                {!! Form::close() !!}

            </td>
        </tr>
    @endforeach