routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::middleware('auth')->get('/home', 'HomeController@index');

Route::get('/', 'HomeController@index')->name('home');

Route::resource('users', 'UserController', ['except' => 'show']);

Route::resource('roles', 'RoleController', ['except' => 'show']);

Route::resource('permissions', 'PermissionController', ['except' => 'show']);

// not needed
//Route::resource('posts', 'PostController');

// business routes
//Route::resource('subscriptions/subscribe', 'SubscriptionController@subscribe');
Route::resource('subscriptions', 'SubscriptionController', ['except' => ['create', 'show']]);

Route::resource('systems', 'SystemController', ['only' => ['index', 'edit', 'update']]);

Route::resource('recipients', 'RecipientsController', ['except' => ['create', 'show']]);

Route::resource('groups', 'GroupController', ['except' => ['create', 'show']]);

//Route::resource('in', 'OzekiInController');

Route::resource('out', 'OzekiOutController', ['only' => ['index', 'store']]);

Route::resource('credits', 'CreditController', ['only' => ['index', 'create', 'store', 'update']]);

Route::resource('sms-categories', 'SmsCategoryController',  ['only' => ['destroy' ,'edit', 'update', 'store']]);

//Route::resource('memberships', 'MembershipController');

Route::resource('billing', 'BillingController',  ['only' => ['index', 'show', 'edit', 'update']]);

Route::resource('profile', 'CustomerInfoController',  ['only' => ['edit', 'update']]);

Route::resource('reports', 'ReportsController',  ['only' => ['index', 'update', 'store']]);

Route::resource('invoices', 'InvoiceController',  ['only' => ['show', 'store']]);

resources/views/partials/reporting/daily_report.blade.php
<div class="panel panel-default panel-body">
        <div class="row">
            <div class="col-md-12" >
                <div class="col-md-6">
                    <div class="card mb-3 panel panel-primary btn-outline-info text-center">
                        <div class="card-header">
                            @if(\Illuminate\Support\Facades\Auth::user()->hasRole('Admin'))
                                Total Messages Sent By Users This Month
                            @else
                                SMS Sent This Month
                            @endif
                        </div>
                        <div class="card-body">
                            <h1>{{ $total_messages_for_the_month }} <i class="fa fa-arrow-up"></i></h1>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 pull-right">
                    @if(\Illuminate\Support\Facades\Auth::user()->hasrole('Admin'))
                        {{-- Nothing should be displayed --}}
                    @else
                        <div class="card mb-3 panel panel-primary btn-outline-info text-center">
                            <div class="card-header">Available SMS Credit</div>
                            <div class="card-body">
                                <span> <h1><i class="fa fa-dollar"></i>  {{   round(\Illuminate\Support\Facades\Auth::user()->sms_credit, 2)}} </h1> </span>
                            </div>
                        </div>
                    @endif
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-md-12" >
                <div class="card mb-3 panel panel-primary">
                    <div class="card-header text-center">Monthly Stats</div>
                    <div class="card-body">
                        {!! $monthly_stats_chart->html() !!}
                    </div>
                </div>
            </div>
        </div>
</div>

resources/views/partials/reporting/financial_reports.blade.php
@component('components.tables.table')

@slot('title', 'Financial Report' )

{{--<a href="{{ route('users.create') }}" class="btn btn-success">Add User</a>--}}
@include('partials.forms.financial_report')

@slot('thead')
    @include('partials.reporting.headers.financial_reporting')
@endslot

@slot('tfoot')
    {{--@include('partials.reporting.headers.financial_reporting')--}}
@endslot

@slot('tbody')
    @include('partials.reporting.data.fa_monthly')
@endslot

@slot('card_footer')
Updated yesterday at 11:59 PM
@endslot
@endcomponent

resources/views/partials/reporting/monthly_report.blade.php
<div class="panel panel-default panel-body">
   <div class="row">
       <div class="col-md-3 text-center" >
           <div class="card mb-3  panel panel-primary btn-outline-info">
               <div class="card-header">SMS Sent Statistics For This Month</div>
               <div class="card-body">
                   {{--<h1>{{ $total_messages_for_the_month }} <i class="fa fa-arrow-up"></i></h1>--}}
               </div>
               {{--<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>--}}
           </div>
       </div>
   </div>
    <div class="row">
        <div class="col-md-8" >
            <div class="card mb-3 panel panel-primary btn-outline-info">
                <div class="card-header">Current Month Stats</div>
                <div class="card-body">
                    {{--{!! $monthly_stats_chart->html() !!}--}}
                </div>
                {{--<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>--}}
            </div>
        </div>
    </div>
</div>

resources/views/partials/reporting/sms_reports.blade.php
@component('components.tables.table')

@slot('title', 'SMS Report' )
@slot('default')
{{--customise the data-table here--}}
    <script>
        $(document).ready(function(){
            $(".dataTable").DataTable()
        });
    </script>
@endslot
<br>
{{-- filtering forms and modals are found in this file --}}
@include('partials.forms.sms_report')
<br>
@slot('thead')
    @if($day)
        <span class="text-center" style="text-decoration-line: underline"><h4 ><strong>Daily Report</strong></h4></span>
        @include('partials.reporting.headers.day')
    @endif

    @if($month)
        <span class="text-center" style="text-decoration-line: underline"><h4 ><strong>Monthly Report</strong></h4></span>
        @include('partials.reporting.headers.month')
    @endif

    @if($year)
        <span class="text-center" style="text-decoration-line: underline"><h4 ><strong>Yearly Report</strong></h4></span>
        @include('partials.reporting.headers.year')
    @endif

@endslot

@slot('tfoot')
    @if($day)
        @include('partials.reporting.headers.day')
    @endif

    @if($month)
        @include('partials.reporting.headers.month')
    @endif

    @if($year)
        @include('partials.reporting.headers.year')
    @endif
@endslot

@slot('tbody')

@if($year)
    @include('partials.reporting.data.yearly_report')
@endif
@if($day)
    @include('partials.reporting.data.daily_report')
@endif
@if($month)
    @include('partials.reporting.data.monthly_report')
@endif
@endslot

@slot('card_footer')
Updated yesterday at 11:59 PM
@endslot
@endcomponent

resources/views/partials/reporting/weekly_report.blade.php
<div class="panel panel-default panel-body">
    <div class="col-md-4" >
        <div class="card mb-3 panel panel-primary btn-outline-info">
            <div class="card-header">SMS Sent Statistics For This Week</div>
            <div class="card-body">
                {{--<h1>{{ $total_messages_for_the_week }} <i class="fa fa-arrow-up"></i></h1>--}}
            </div>
            {{--<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>--}}
        </div>
        {{--<div class="card mb-3">--}}
        {{--<div class="card-header">Remaining SMS Credit</div>--}}
        {{--<div class="card-body">--}}
        {{--<span> <h1><i class="fa fa-dollar"></i>  {{   round(\Illuminate\Support\Facades\Auth::user()->sms_credit, 2)}} </h1> </span>--}}
        {{--</div>--}}
        {{--<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>--}}
        {{--</div>--}}
    </div>
    <div class="col-md-8" >
        <div class="card mb-3 panel panel-primary btn-outline-info">
            <div class="card-header">Current Week Stats</div>
            <div class="card-body">
                {{--{!! $weekly_stats_chart->html() !!}--}}
            </div>
            {{--<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>--}}
        </div>
    </div>
</div>